language: php
php:
  - "5.6"
  - "7.0"
before_script:
  - composer install
script:
  - phpunit --coverage-clover build/logs/clover.xml
services: ~
after_success:
  - travis_retry php vendor/bin/coveralls -v